### PR TITLE
Rebuild for gdal34,proj820,geos3101 and workaround cross-compile issue and migrate off Travis

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This provides a workaround to the cross-compile issue in conda-forge/r-base-feedstock#163

It also migrates three things at once to avoid dependency issues.

:eyes: CI

### CODE REVIEW

**Comment by akrherz** [comment]
Grumble, Travis-CI flakeness.  Will migrate that too...

**Comment by akrherz** [comment]
Failure
```
2021-12-09T15:52:33.1073517Z   unable to load shared object '$PREFIX/lib/R/library/Rcpp/libs/Rcpp.so':
2021-12-09T15:52:33.1080088Z   $PREFIX/lib/R/library/Rcpp/libs/Rcpp.so: cannot open shared object file: No such file or directory
```
I have seen this before, googling around.

**Comment by akrherz** [comment]
It appears the `cross-r-base` package does this that I don't fully understanding in this new cross compile situation.  Rewriting git history now to clean this up.  Ready for review...

**Comment by akrherz** [comment]
Hi @cbrueffer, I have another green PR for your consideration.  Or if anybody else watching is able to review this? :)

**Comment by dbast** [comment]
thanks!

**Pull request merged**
